name: Tests
'on':
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Node ${{ matrix.node }}
    strategy:
      matrix:
        node:
          - '10'
          - '12'
          - '14'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: make test

  test-targets:
    runs-on: ubuntu-18.04
    name: ${{ matrix.targets.name }}
    strategy:
      matrix:
        targets:
          - { target: 'coverage', name: 'Coverage' }
          - { target: 'test-jest', name: 'Jest' }
          - { target: 'test-jasmine', name: 'Jasmine' }
          - { target: 'test-plugins', name: 'Plugins' }
          - target: 'test-browserstack-ie11'
            name: 'Browser - IE11'
            env:
              BROWSER_STACK_ACCESS_KEY: '${{ secrets.BROWSER_STACK_ACCESS_KEY }}'
              BROWSER_STACK_USERNAME: '${{ secrets.BROWSER_STACK_USERNAME }}'
          - { target: 'test-deno', name: 'Deno' }
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: make ${{ matrix.targets.target }}
